[package]
name = "rust-c"
version = "0.1.0"
authors = ["Klas Segeljakt <klasseg@kth.se>"]
edition = "2018"

[lib]
name = "foo"
crate-type = ["staticlib"]

[build-dependencies]
cc = "1.0.61"

[dependencies]
